# Generated by Django 4.0.1 on 2022-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='town_city',
            field=models.CharField(max_length=150, verbose_name='Town/City/Province'),
        ),
    ]
